name: auto-update

on:
  workflow_dispatch:
  schedule:
    - cron:  0 */4 * * *

jobs:
  build:
    name: auto update
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: liamg/github-profile-terminal-action@main
      with:
        feed_url: https://ferhatelmas.com/rss.xml
        twitter_username: ferhatelmas_
        theme: dark
        token: ${{ secrets. GITHUB_TOKEN }}
        #extra_repo: ferhatelmas/some
        #extra_repo_description: "some notes"
