name: Auto Approve

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.actor == 'imgbot[bot]'
    steps:
    - name: Auto Approve
      uses: hmarr/auto-approve-action@v3.2.1
      with:
        github-token: ${{ secrets.METRICS_TOKEN }}
    - name: Merge
      uses: squalrus/merge-bot@v0.4.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        labels: ""
        method: squash
