name: Update README

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: muesli/readme-scribe@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: github-actions[bot]
          commit_user_email: actions@github.com
          commit_author: github-actions[bot] <actions@github.com>
